apiVersion: v1
kind: Namespace
metadata:
  name: demos
  labels:
    name: demos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  namespace: demos
  labels:
    app: grpc-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - name: grpc-server
          image: innfocco/grpc-server:latest
          ports:
            - containerPort: 7565
---
kind: Service
apiVersion: v1
metadata:
  name: grpc-server-svc
  namespace: demos
spec:
  type: ClusterIP
  selector:
    app: grpc-server
  ports:
    - name: tcp
      protocol: TCP
      port: 7565
      targetPort: 7565

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
  namespace: demos
  labels:
    app: grpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: innfocco/grpc-client:latest
          env:
            - name: GRPC_SERVER_HOST
              value: "grpc-server-svc"